# Chọn base image cho React
FROM node:18-alpine

# Set thư mục làm việc trong container
WORKDIR /app

# Copy package.json và cài đặt dependencies
COPY package.json yarn.lock ./
RUN yarn install

# Copy toàn bộ mã nguồn vào container
COPY . .

# Build React app
RUN yarn build

# Expose port cho React frontend
EXPOSE 3000

# Chạy React app
CMD ["yarn", "start"]